repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e
    hooks:
      - id: fmt
      - id: clippy
        args: ["--tests", "--all", "--", "-D", "warnings", "-A", "dead_code", "-D", "clippy::semicolon-if-nothing-returned"]
