[package]
name = "cmdparse"
version = "0.1.0"
edition = "2021"

[dependencies]
cmdparse-derive = { path = "../cmdparse-derive" }

[dev-dependencies]
tempdir = "0.3"

# Example dependencies
rustyline = "9.1.0"
smallvec = "1.8.0"
